# Generated by Django 4.1.7 on 2023-02-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profiles',
            table='profiles',
        ),
    ]
